### PR TITLE
Faster build Time 

### PR DESCRIPTION
**Pull request by siddarthvader**
### Build time was approximately 3-4 minutes on second build and was 10-12 minutes on very first build.

After making these changes

- Replaced typescript compiler `tsc` with `swc`, introduced a .swcrc file as config
- not instaling deps in gs-node-service on every build
- not deleting node_modules, package-lock.json from /dist folder
- conditional install for elasticgraph submodule

### Now We have build time of 50 seconds on second build and 6-8 minutes on very first build.

[Check this Notion Doc for details RCA and analysis](https://www.notion.so/siddocumenting/Godspeed-Build-time-Benchmarking-7a6a6306e1bc4b90be5c21162fbc94c0?pvs=4)

#446

### CODE REVIEW

**Comment by siddarthvader** [comment]
@ashutoshmindgrep i am confident about the most the of changes except for the swc part, could you run it on your machine and see how it goes, i am asking other folks to test as well, lets have that coverage.

**Review by sambamindgrep — APPROVED** [review]

**Comment by ashutoshmindgrep** [comment]
@siddarthvader Sure. I will test it before today EOD.

**Comment by arunsingh** [comment]
I tried with the earlier version, build time for first build is up to 15-20min. Once index is built it takes up to 5mins, With this new build-optimization it is taking up to 10mins on my machine, post that once index is built pnpm is taking < 2mins, though app is breaking sometime more. 

@siddarthvader It will be nice if you can write step by step procedure for how to test this on local machine, especially for new people on the team. So that more people test this out and come up with bug reporting.

**Comment by siddarthvader** [comment]
outdated since new cli is not stable, will bring it back.

**Pull request closed without merging**
