### PR TITLE
Build optimization.

### PR DESCRIPTION
**Pull request by siddarthvader**
### Build time was approximately 3-4 minutes on second build and was 10-12 minutes on very first build.

After making these changes

- Replaced typescript compiler `tsc` with `swc`, introduced a .swcrc file as config
- not instaling deps in gs-node-service on every build
- not deleting node_modules, package-lock.json from /dist folder
- conditional install for elasticgraph submodule

### Now We have build time of almost 2 minutes on second build and 6-8 minutes on very first build.

[Check this Notion Doc for details RCA and analysis](https://www.notion.so/siddocumenting/Godspeed-Build-time-Benchmarking-7a6a6306e1bc4b90be5c21162fbc94c0?pvs=4)

#446

### CODE REVIEW

**Comment by siddarthvader** [comment]
Steps to test

- godspeed create <project name>
- pull `fb1.0` version while creating
- open folder in container
- go to ../gs_service
- `npm install
`- create a file .swcrc and copy the content from this pull request
- come back to /app folder
- run `time npm run build`
- run `npm run dev`

**Comment by siddarthvader** [comment]
@avtar-mindgrep @ssuda  
There is one thing, I have committed and pushed a new file `.swcrc` for config and it is there in the repo but when I pull this tag(`fb1.0` while using `godspeed create`) the file does not get pulled. Any idea why this must be happening?

**Comment by siddarthvader** [comment]
> @avtar-mindgrep @ssuda There is one thing, I have committed and pushed a new file `.swcrc` for config and it is there in the repo but when I pull this tag(`fb1.0` while using `godspeed create`) the file does not get pulled. Any idea why this must be happening?

got it working, no worries.

**Review by sambamindgrep — APPROVED** [review]

**Comment by ashutoshmindgrep** [comment]
@siddarthvader I think we are good t merge this. Can you please resolve the conflicts.

**Comment by siddarthvader** [comment]
@ashutoshmindgrep conflict resolved

**Review by ashutoshmindgrep — APPROVED** [review]

**Comment by ashutoshmindgrep** [comment]
@siddarthvader Let's merge.

**Pull request merged**
